language: node_js
sudo: false
node_js:
  - 0.12

env:
  global:
  - SAUCE_USERNAME=Cherrytree-ko
  - secure: "KMtdy3zHZaHMW1NGjv6ptbNP72eB2WTi2bDMpCQWB5S1hq4hsE2RaTmytlzMZ0rToMuPi12FOtWR5vSLFZ4JgGaDUsSP461trk8O+8XEb/30eUYh7sRSjlclQaqf3fdEtgqBiUagvTz2yecqoEK71UXD5Bi9kORt+ECx2d6N8qT5pnu1S0A2Q1gfG1oDaj3i3JZYa3AwNl9+Ts+xaKFn5190VG4BLoY08QpHK1hbthinmyZIL1zwpq/aA9iOEAsYgub+DBC7ZZ1HIFyF76qnj+Gq3gbrhPxQ9mIPqf5rW/UMSjAvYKUguQYcR0psZ4fT++G7hnRaziMA1gT2rDPi73Qmdma9vw1rqrPjjB3jEycpmsxP2tBoNuCqceROeNWyKns46ySulxCEUn9UhRFtUmbTr0+Fpd50dQfClF2vS+YxIyBhe37F8JoljWZjopUh7WZM1y97Pj1a3zmZK8PyTjlfdnrkhcJ2klvGFkAVSoow42fp/S6QupU6qSywjdapQaHqfBhzYwFItuv0G9qbuQqQWQyfPpMs+/L1MZ95FXlZMnDe+KogERAvDarIkma07a/11iMvvefVZjFOx2EmakRgDURnNEHEudTgH8lOC/bjs0ca+lhx0BrqufR8N7PwHSyofA+83qMdsly8geSlG33MzHQh/K8I5OjSuOEq9NU="

script: npm test
